import React from "react";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 30,
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  header: {
    fontSize: 24,
    textAlign: "center",
    marginBottom: 20,
    color: "#1a202c",
  },
  subHeader: {
    fontSize: 18,
    marginBottom: 10,
    color: "#2d3748",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingBottom: 5,
  },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    fontSize: 12,
  },
  resultLabel: {
    color: "#4a5568",
  },
  resultValue: {
    fontWeight: "bold",
    color: "#1a202c",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    color: "grey",
    fontSize: 10,
  },
});

// 1. Define specific interfaces for the data
interface ResultsData {
  monthly_savings: number;
  payback_months: number | string;
  roi_percentage: number | string;
}

interface InputsData {
  monthly_invoice_volume: number;
  num_ap_staff: number;
  hourly_wage: number;
}

// 2. Use the specific interfaces instead of 'any'
interface ReportDocumentProps {
  data: {
    scenario_name?: string;
    results: ResultsData;
    inputs: InputsData;
  };
}

// Create Document Component
export const ReportDocument: React.FC<ReportDocumentProps> = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View>
        <Text style={styles.header}>Invoicing Automation ROI Report</Text>

        {data.scenario_name && (
          <Text style={styles.subHeader}>Scenario: {data.scenario_name}</Text>
        )}

        <View style={styles.section}>
          <Text style={styles.subHeader}>Key Results</Text>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>Estimated Monthly Savings</Text>
            <Text style={styles.resultValue}>
              ${data.results.monthly_savings.toLocaleString()}
            </Text>
          </View>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>Payback Period (Months)</Text>
            <Text style={styles.resultValue}>
              {data.results.payback_months}
            </Text>
          </View>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>Return on Investment (ROI)</Text>
            <Text style={styles.resultValue}>
              {data.results.roi_percentage}%
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.subHeader}>Based on Inputs</Text>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>Monthly Invoices</Text>
            <Text style={styles.resultValue}>
              {data.inputs.monthly_invoice_volume.toLocaleString()}
            </Text>
          </View>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>AP Staff Size</Text>
            <Text style={styles.resultValue}>{data.inputs.num_ap_staff}</Text>
          </View>
          <View style={styles.resultRow}>
            <Text style={styles.resultLabel}>Avg Hourly Wage</Text>
            <Text style={styles.resultValue}>${data.inputs.hourly_wage}</Text>
          </View>
        </View>
      </View>
      <Text style={styles.footer}>Generated by Invoicing ROI Simulator</Text>
    </Page>
  </Document>
);
